### ISSUE TITLE
Typescript - AbstractNode constructor function signature - error

### ISSUE THREAD

**Issue by ak99372** [dodevops/js-hierarchy#1]
when using example code in Typescript, the constructor's definition doesn't support custom object as argument

`var rootNode = new SimpleNode({ 'name': 'root' });`

will result in 

**Argument of type '{ 'name': string; }' is not assignable to parameter of type 'string'.**

from AbstractNode.d.ts
```
constructor(name?: string, data?: {
        [p: string]: any;
    });
```

**Comment by dploeger** [comment]
Ah, yes. Sorry. The documentation wasn't updated with the latest release, which expects nodes to have a name. Fixed that. Thanks for pointing it out.
