### ISSUE TITLE
left / right purpose?

### ISSUE THREAD

**Issue by davestewart** [dodevops/js-hierarchy#2]
Hi,

I'm just looking around for a good, general purpose hierarchical lib, and came across this.

I've not seen the left / right functionality before (except maybe in SQL / sets, but that's different, right?). What is the use case here?

Thanks.

**Comment by dploeger** [comment]
This feature currently is just there, because it "was possible". 😆 
We're not currently using it in any dependent project, it was just so easy to implement, that we did it. But, yes, the feature is very different vom SQL, it just walks to the neighboring nodes in the tree, that have the same parent. (I only know left/right in SQL with joins. Or do you mean something different?)

**Comment by dploeger** [comment]
BTW, js-hierarchy is really supposed to be a good, general purpose hierarchical lib. So if you have any issues, please report them. Thanks!

**Comment by davestewart** [comment]
> I only know left/right in SQL with joins

There's a way to model hierarchical data in a flat table by storing the min and max parent ids for a (child?) branch, so you query on that when finding children. It's supposed to be performant on read at the expense of needing to rebuild on write if you alter the structure (I think!)

Ah yes, here it is (see the left right labels in the table): https://en.wikipedia.org/wiki/Nested_set_model

Can you say what projects you're using it in at the moment?

How do you persist and sync data (if you do) to something like firebase? I've yet to use FB, so I'm just hacking around at the moment to see what might work :)

**Comment by dploeger** [comment]
> Ah yes, here it is (see the left right labels in the table): https://en.wikipedia.org/wiki/Nested_set_model

Ah, okay. I didn't think about implementations of that model in relational databases.

> Can you say what projects you're using it in at the moment?

It's currently the foundation for our [SOCKO Framework](https://github.com/dodevops/socko). For the persistence part, we're using [file-hierarchy](https://github.com/dodevops/file-hierarchy) there, so no very fancy stuff. And we don't do syncing currently. (And that would be a very interesting feature actually 😁 )

**Comment by davestewart** [comment]
I was just checking the dependencies on NPM actually, and it answered my next question - why promises? Makes sense now, and why you return resolved promises in the base version of the lib :)

**Comment by dploeger** [comment]
:) I actually forgot them in the first version and had to implement them later because of Socko.

**Comment by davestewart** [comment]
Design decisions!

**Comment by dploeger** [comment]
Yes, well... 😆

**Comment by dploeger** [comment]
@davestewart Is something still open in this issue or can it be closed?

**Comment by davestewart** [comment]
Yup, I didn't use it in the end, but enjoyed the chat!

**Comment by dploeger** [comment]
Great, thanks.
