### ISSUE TITLE
Promise dependency

### ISSUE THREAD

**Issue by r3mi** [dodevops/js-hierarchy#3]
nice library, thanks.
To reduce external dependencies, would you consider switching to native promises ?
Alternatively, letting the user choose, eg with [any-promise](https://github.com/kevinbeaty/any-promise) or equivalent ?

**Comment by dploeger** [comment]
Thanks for checking it out.

I'm using Bluebird's reduce function [here](https://github.com/dodevops/js-hierarchy/blob/master/lib/AbstractNode.ts#L173). Native promises doesn't support this, right? So we'd need to reimplement that.

I'm open for this, although I quite like Bluebird. So going the promise adapter way seems nice. You care to do a PR for this?

**Comment by r3mi** [comment]
thanks for the quick reply.
I didn't realise that there was usage of specific bluebird functions. You are right, `reduce` is not in the standard.
So may be it is simpler to leave the bluebird dependency, rather than re-implement...

**Comment by dploeger** [comment]
Yes, probably. I'll close this then.
